import React from 'react';
import Layout from './layout'
import image from '../../images/LAT/organise.png'

const Index = () => (
  <Layout
    title="ORGANISER"
    image={image}
    list={[
      'Organize yourself - creating monthly/weekly and daily work schedules and managing `lime bandits`.',
      'Control how work is generated by customers, the system, and your manager.',
      'Establish good relationships with your manager by understanding his/her objectives and priorities and helping to achieve them.',
      'Review and define the way work is processed through mapping work flows. These can contribute towards accreditation for international standards.',
      'Emphasize good housekeeping: a home for everything, clear out regularly, clean and check,set standards, routine maintenance.',
      'Agree who does what and when. Systematically monitor the quality, quantity and speed of output.'
    ]}
    to='/leadership-skills/'
  />
);

export default Index;
