import React from 'react';
import {
  Link,
} from "react-router-dom";

const Index = () => (
  <div className="">
    <h4 style={{
      color: `#565347`,
    }}>
      ORGANISER
    </h4>
    <div>
      <ul>
        <li>Organize yourself - creating monthly/weekly and daily work schedules and managing 'lime bandits'.</li>
        <li>Control how work is generated by customers, the system, and your manager.</li>
        <li>Establish good relationships with your manager by understanding his/her objectivesandpriorities andhelpingtoachievethem.</li>
        <li>Reviewanddefinethe wayworkisprocessedthroughmappingworkflows These can contribute towards accreditation for international standards.</li>
        <li>Emphasize good housekeeping: a home for everything, clear out regularly, cleanandcheck,setstandards, routinemaintenance.</li>
        <li>Agree who does what and when. Systematically monitor the quality, quantity and speed of output.</li>
      </ul>
    </div>
    <Link style={{ justifyContent: 'flex-end'}} to="/leadership-skills/">
    <h5 style={{
      color: `#565347`,
    }}>
        back
    </h5></Link>

  </div>
);

export default Index;
